
package ee.ut.smartadtool.ui;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import ee.ut.smarttool.DB.AssetDBSerivice;
import ee.ut.smarttool.DB.VulnerabilityDBService;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import ee.ut.smartadtool.service.DataPopulator;
import javax.swing.JSeparator;
import javax.swing.JTable;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Salman
 */
public class EditAsset extends javax.swing.JFrame {

    private Object[][] data;
    int activeTab;
	/**
     * Creates new form EditAsset
     * @throws Exception 
     */
    public EditAsset() throws Exception {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws Exception 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    public void populateDataToTable(JTable table,Object [][] data,String [] columns){
        System.out.println(""+jTabbedPane1.getSelectedIndex());
        activeTab=jTabbedPane1.getSelectedIndex();
        try {
		//	data = DataPopulator.DataPreprocessor(asset.selectAll("asset"));
        	table.setModel(new javax.swing.table.DefaultTableModel(data,columns) );
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
    }
    private void initComponents() throws Exception {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        vulnerabilityTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		VulnerabilityDBService vulDBServic= new VulnerabilityDBService();
        		try {
					vulDBServic.insertVulnerability(vulnerabilityTF.getText(), vulnerabiltyTA.getText());
				} catch (Exception e1) {
					e1.printStackTrace();
				}
        	}
        });
        jButton2.setBackground(Color.GREEN);
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        editAssetTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editValueTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editAttackedNumberTF = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        updateButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        //	System.out.println(assetID.getText()+" "+editAssetTF.getText()+" "+editValueTF.getText()+" "+editAttackedNumberTF.getText()+" "+editDescriptionTF.getText());
           AssetDBSerivice assetDBSerivice= new AssetDBSerivice();
           try {
        	Object[][] dataForTable = DataPopulator.DataPreprocessor(assetDBSerivice.selectAll("asset"));
        	String [] columns=  DataPopulator.getColumn(assetDBSerivice.selectAll("asset"));
			populateDataToTable(jTable1,dataForTable,columns);
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
           try {
            	assetDBSerivice.updateAsset(editAssetTF.getText(),editDescriptionTF.getText() ,editValueTF.getText(), editAttackedNumberTF.getText(), assetID.getText());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        	}
        });
        jSeparator1 = new javax.swing.JSeparator();
        delleteButton = new javax.swing.JButton();
        delleteButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		AssetDBSerivice assetDBSerivice= new AssetDBSerivice();
        		try {
					assetDBSerivice.delete("asset", assetID.getText());
					   try {
						    Object[][] assetsData = DataPopulator.DataPreprocessor(assetDBSerivice.selectAll("asset"));
						    String [] assetColumns= DataPopulator.getColumn(assetDBSerivice.selectAll("asset"));
							populateDataToTable(jTable1,assetsData,assetColumns);
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
            	
        	}
        });
        jLabel10 = new javax.swing.JLabel();
        editVulnerabilityPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        editVulnerabilityTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        editVulnerabilityDescriptionTA = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		VulnerabilityDBService vul=new VulnerabilityDBService();
        		try {
					vul.updateAsset(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString(), editVulnerabilityTF.getText(), editVulnerabilityDescriptionTA.getText());
					VulnerabilityDBService vulnerabilityDBServicee=new VulnerabilityDBService();
           			Object[][] vulnerabilityData= DataPopulator.DataPreprocessor(vulnerabilityDBServicee.selectAll("vulnerability"));
           			String [] VulnerabilitiesColumns=DataPopulator.getColumn(vulnerabilityDBServicee.selectAll("vulnerability"));
           		
					populateDataToTable(jTable2, vulnerabilityData, VulnerabilitiesColumns);
        		} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
        	}
        });
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		VulnerabilityDBService vulnerabilityDBServicee=new VulnerabilityDBService();
       			try {
					Object[][] vulnerabilityData= DataPopulator.DataPreprocessor(vulnerabilityDBServicee.selectAll("vulnerability"));
					String [] VulnerabilitiesColumns=DataPopulator.getColumn(vulnerabilityDBServicee.selectAll("vulnerability"));
					try{
					vulnerabilityDBServicee.delete("vulnerability",(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString()));
					}catch(Exception e2){}
					populateDataToTable(jTable2, vulnerabilityData, VulnerabilitiesColumns);
				} catch (Exception e1) {
					
					e1.printStackTrace();
				}
        	}
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jTabbedPane1.addChangeListener(new ChangeListener() { //add the Listener

            public void stateChanged(ChangeEvent e) {
            	try {

					if(jTabbedPane1.getSelectedIndex()==2){
	            		AssetDBSerivice assetDBSerivice=new AssetDBSerivice();
	            		Object[][] assetData= DataPopulator.DataPreprocessor(assetDBSerivice.selectAll("asset"));
	            		String[] columns= DataPopulator.getColumn(assetDBSerivice.selectAll("asset"));
	           			populateDataToTable(jTable1,assetData,columns);
					}if(jTabbedPane1.getSelectedIndex()==3){
	           			VulnerabilityDBService vulnerabilityDBServicee=new VulnerabilityDBService();
	           			Object[][] vulnerabilityData= DataPopulator.DataPreprocessor(vulnerabilityDBServicee.selectAll("vulnerability"));
	           			String [] VulnerabilitiesColumns=DataPopulator.getColumn(vulnerabilityDBServicee.selectAll("vulnerability"));
	           			populateDataToTable(jTable2,vulnerabilityData,VulnerabilitiesColumns);
	           		}
	           			
            	} catch (Exception e1) {
           			// TODO Auto-generated catch block
           			e1.printStackTrace();
           		}
            }
        });


        jLabel8.setText("Vulnerability");

        jLabel9.setText("Description");

        jButton2.setText("Create Vulnerabilty");
        vulnerabiltyTA = new javax.swing.JTextArea();
        
                vulnerabiltyTA.setColumns(20);
                vulnerabiltyTA.setRows(5);
        
        lblType = new JLabel("Type");
        
        JComboBox comboBox = new JComboBox();
        comboBox.setModel(new DefaultComboBoxModel(new String[] {"Level 1", "Level 2", "Level 3"}));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(248, Short.MAX_VALUE)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
        			.addGap(152))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(63)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel8)
        				.addComponent(jLabel9)
        				.addComponent(lblType))
        			.addGap(49)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(vulnerabiltyTA, GroupLayout.PREFERRED_SIZE, 387, GroupLayout.PREFERRED_SIZE)
        				.addComponent(vulnerabilityTF, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
        				.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(66)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(vulnerabilityTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblType)
        				.addComponent(comboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(42)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(vulnerabiltyTA, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
        					.addComponent(jButton2)
        					.addGap(93))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel9)
        					.addContainerGap())))
        );
        jPanel3.setLayout(jPanel3Layout);

        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
            	try{
            		if(activeTab==2){
		                assetID.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
		                editAssetTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
		                editValueTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
		                editAttackedNumberTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
		                editDescriptionTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            		}
            		if(activeTab==3){
            			
            			editVulnerabilityTF.setText(jTable2.getValueAt(jTable2.getSelectedRow(),1).toString());
            			editVulnerabilityDescriptionTA.setText(jTable2.getValueAt(jTable2.getSelectedRow(),2).toString());
            		}
            	}catch(Exception e){
            		
            	}
            }
        });
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
            	try{
                // do some actions here, for example
                // print first column value from selected row
           //     System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                assetID.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                editAssetTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
                editValueTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
                editAttackedNumberTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
                editDescriptionTF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            	}catch(Exception e){
            		
            	}
            }
        });
        jTabbedPane1.addTab("Create New Vulnerability", jPanel3);
       

        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel4.setText("Asset Name");

        jLabel5.setText("Value");

        jLabel6.setText("Attacked Number");

        updateButton.setBackground(new java.awt.Color(0, 255, 0));
        updateButton.setText("Update");

        delleteButton.setBackground(new java.awt.Color(255, 0, 51));
        delleteButton.setText("Delete the selected asset");

        jLabel10.setText("Description");
        
        assetID = new JLabel("Selected ID");
        
        JSeparator separator = new JSeparator();
        editDescriptionTF = new javax.swing.JTextArea();
        
                editDescriptionTF.setColumns(20);
                editDescriptionTF.setRows(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(204)
        					.addComponent(delleteButton, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(separator, GroupLayout.PREFERRED_SIZE, 555, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(57)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(assetID)
        									.addComponent(jLabel10))
        								.addComponent(jLabel4))
        							.addGap(18)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(editAssetTF, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(jLabel5)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(editValueTF, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(jLabel6)
        									.addGap(8)
        									.addComponent(editAttackedNumberTF, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)
        									.addGap(6))
        								.addComponent(editDescriptionTF, GroupLayout.PREFERRED_SIZE, 469, GroupLayout.PREFERRED_SIZE))))
        					.addPreferredGap(ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(213)
        					.addComponent(updateButton, GroupLayout.PREFERRED_SIZE, 222, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(35)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 566, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(16)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(15)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(editAssetTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel5)
        								.addComponent(jLabel4))
        							.addPreferredGap(ComponentPlacement.UNRELATED))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        									.addComponent(editAttackedNumberTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jLabel6))
        								.addComponent(editValueTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)))
        					.addComponent(editDescriptionTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(89)
        					.addComponent(jLabel10)))
        			.addGap(16)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(33)
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(updateButton)
        						.addComponent(assetID))
        					.addGap(18)
        					.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(28)
        			.addComponent(delleteButton)
        			.addContainerGap(84, Short.MAX_VALUE))
        
        		);
        jPanel1.setLayout(jPanel1Layout);
        assetID.setVisible(false);
        jTabbedPane1.addTab("Edit Asset", jPanel1);

        jLabel11.setText("Vulnerability");
        
    /*    jTabbedPane2.addChangeListener(new ChangeListener() { //add the Listener

            public void stateChanged(ChangeEvent e) {
            	try {
            		VulnerabilityDBService vulnerabilityDBServicee=new VulnerabilityDBService();
           			populateDataToTable(jTable2,DataPopulator.DataPreprocessor(vulnerabilityDBServicee.selectAll("vulnerability")));
           		} catch (Exception e1) {
           			// TODO Auto-generated catch block
           			e1.printStackTrace();
           		}
            }
        }); */
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Vulnerability", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jLabel12.setText("Description");

        editVulnerabilityDescriptionTA.setColumns(20);
        editVulnerabilityDescriptionTA.setRows(5);
        jScrollPane5.setViewportView(editVulnerabilityDescriptionTA);

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setText("Update Selected Vulnerability");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Delete Selected Vulnerability");

        javax.swing.GroupLayout editVulnerabilityPanelLayout = new javax.swing.GroupLayout(editVulnerabilityPanel);
        editVulnerabilityPanel.setLayout(editVulnerabilityPanelLayout);
        editVulnerabilityPanelLayout.setHorizontalGroup(
            editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editVulnerabilityPanelLayout.createSequentialGroup()
                .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editVulnerabilityPanelLayout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editVulnerabilityPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(editVulnerabilityPanelLayout.createSequentialGroup()
                                .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(102, 102, 102)
                                .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editVulnerabilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editVulnerabilityPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        editVulnerabilityPanelLayout.setVerticalGroup(
            editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editVulnerabilityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editVulnerabilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editVulnerabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editVulnerabilityPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12))
                    .addGroup(editVulnerabilityPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jButton3)
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Vulnerabilities", editVulnerabilityPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 859, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jTabbedPane1, GroupLayout.PREFERRED_SIZE, 335, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(128, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        assetNameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valueTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        	//	System.out.println(assetNameTF.getText()+" "+valueTF.getText()+" "+jSpinner1.getValue()+assetDescriptionTA.getText());
        		AssetDBSerivice assetDBSerivice=new AssetDBSerivice();
        		try {

					assetDBSerivice.insert(assetNameTF.getText(),assetDescriptionTA.getText() ,valueTF.getText(), jSpinner1.getValue().toString());
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        });
        jLabel7 = new javax.swing.JLabel();
        vulnerabilityCombo = new javax.swing.JComboBox<>();
        
                jLabel3.setText("Asset Name");
                
                        jLabel1.setText("Value ");
                        
                                jLabel2.setText("Number of Attacks");
                                
                                        jButton1.setText("Add Asset");
                                        
                                                jLabel7.setText("Vulnerability");
                                                
                                                        vulnerabilityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                                                        
                                                        JLabel lblDescription = new JLabel("Description");
                                                        
                                                         assetDescriptionTA = new JTextArea();
                                                         
                                                         lblVulnerabilityDescription = new JLabel("Vulnerability Description");
                                                         
                                                         vulnerabilityExplanation = new JLabel("New label");
                                                         
                                                                 javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                                                                 jPanel2Layout.setHorizontalGroup(
                                                                 	jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 		.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 			.addGap(80)
                                                                 			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 				.addComponent(lblDescription)
                                                                 				.addComponent(jLabel2)
                                                                 				.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 						.addComponent(jLabel3)
                                                                 						.addComponent(jLabel1))
                                                                 					.addPreferredGap(ComponentPlacement.RELATED)
                                                                 					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
                                                                 						.addComponent(assetDescriptionTA, GroupLayout.PREFERRED_SIZE, 299, GroupLayout.PREFERRED_SIZE)
                                                                 						.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                 							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 								.addComponent(valueTF)
                                                                 								.addComponent(assetNameTF, GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                                                 								.addComponent(jSpinner1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE))
                                                                 							.addGap(33)
                                                                 							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 								.addComponent(jLabel7)
                                                                 								.addComponent(lblVulnerabilityDescription))))
                                                                 					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 						.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 							.addPreferredGap(ComponentPlacement.RELATED)
                                                                 							.addComponent(vulnerabilityCombo, GroupLayout.PREFERRED_SIZE, 164, GroupLayout.PREFERRED_SIZE))
                                                                 						.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 							.addGap(42)
                                                                 							.addComponent(vulnerabilityExplanation)))))
                                                                 			.addGap(246))
                                                                 		.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 			.addGap(322)
                                                                 			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE)
                                                                 			.addContainerGap(310, Short.MAX_VALUE))
                                                                 );
                                                                 jPanel2Layout.setVerticalGroup(
                                                                 	jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                                 		.addGroup(jPanel2Layout.createSequentialGroup()
                                                                 			.addGap(38)
                                                                 			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                                                 				.addComponent(jLabel3)
                                                                 				.addComponent(assetNameTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                 				.addComponent(jLabel7)
                                                                 				.addComponent(vulnerabilityCombo, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                                                                 			.addPreferredGap(ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                                 			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                                                 				.addComponent(valueTF, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
                                                                 				.addComponent(jLabel1)
                                                                 				.addComponent(lblVulnerabilityDescription)
                                                                 				.addComponent(vulnerabilityExplanation))
                                                                 			.addGap(32)
                                                                 			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                                                 				.addComponent(jLabel2)
                                                                 				.addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
                                                                 			.addGap(18)
                                                                 			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                                                 				.addComponent(lblDescription)
                                                                 				.addComponent(assetDescriptionTA, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
                                                                 			.addGap(40)
                                                                 			.addComponent(jButton1)
                                                                 			.addGap(140))
                                                                 );
                                                                 jPanel2.setLayout(jPanel2Layout);
                                                                 
                                                                         jTabbedPane1.addTab("Add Asset", jPanel2);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAsset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new EditAsset().setVisible(true);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField assetNameTF;
    private javax.swing.JTextField editAssetTF;
    private javax.swing.JTextField editAttackedNumberTF;
    private javax.swing.JButton delleteButton;
    private javax.swing.JTextArea editVulnerabilityDescriptionTA;
    private javax.swing.JTextField editValueTF;
    private javax.swing.JPanel editVulnerabilityPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea editDescriptionTF;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField valueTF;
    private javax.swing.JComboBox<String> vulnerabilityCombo;
    private javax.swing.JTextField editVulnerabilityTF;
    private javax.swing.JTextField vulnerabilityTF;
    private javax.swing.JTextArea vulnerabiltyTA;
    private javax.swing.JTextArea assetDescriptionTA;
    private JLabel assetID;
    private JLabel lblVulnerabilityDescription;
    private JLabel vulnerabilityExplanation;
    private JLabel lblType;
}
