package ee.ut.smartadtool.ui;

import javax.swing.JFrame;

import ee.ut.smartadtool.service.ThreatAgentScoreEvaluatorService;

public class Properties extends javax.swing.JFrame {

    /**
     * Creates new form Properties
     */
    ThreatAgentScoreEvaluatorService taService;
    public Properties() {
        taService=new ThreatAgentScoreEvaluatorService();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        motivationCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        capabilitiesCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        opportunitiesCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ComputerMeansCheckbox = new javax.swing.JCheckBox();
        PeopleAsAssetCheckbox = new javax.swing.JCheckBox();
        ProcessAsAssets = new javax.swing.JCheckBox();
        IntangibleAssetsCheckbox = new javax.swing.JCheckBox();
        StepStoneAssets = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        attackMethodTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        descriptionTA = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        probabilityTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        assetCombo = new javax.swing.JComboBox<>();

     //   setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jLabel5.setText("Motivations");

        motivationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curiosity", "Personal fame", "Personal Gain", "Revenge", "National interest", "Ideology" }));
        motivationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivationComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Capabilities");

        capabilitiesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Undergraduate", "Master", "Specialist" }));
        capabilitiesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capabilitiesComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Opportunities");

        opportunitiesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zero ", "One", "Finite", "Infinite" }));
        opportunitiesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opportunitiesComboActionPerformed(evt);
            }
        });

        jLabel6.setText("Means");

        ComputerMeansCheckbox.setText("Computer means");
        ComputerMeansCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputerMeansCheckboxActionPerformed(evt);
            }
        });

        PeopleAsAssetCheckbox.setText("People as asset");
        PeopleAsAssetCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeopleAsAssetCheckboxActionPerformed(evt);
            }
        });

        ProcessAsAssets.setText("Process as assets");
        ProcessAsAssets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessAsAssetsActionPerformed(evt);
            }
        });

        IntangibleAssetsCheckbox.setText("Intangible assets");
        IntangibleAssetsCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntangibleAssetsCheckboxActionPerformed(evt);
            }
        });

        StepStoneAssets.setText("Step stone assets");
        StepStoneAssets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepStoneAssetsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel7.setText("Threat Agent Score");

        scoreLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        scoreLabel.setText("0.0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(motivationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(capabilitiesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(opportunitiesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProcessAsAssets)
                            .addComponent(ComputerMeansCheckbox)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PeopleAsAssetCheckbox)
                                .addGap(18, 18, 18)
                                .addComponent(StepStoneAssets))
                            .addComponent(IntangibleAssetsCheckbox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(scoreLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(motivationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(capabilitiesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opportunitiesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComputerMeansCheckbox)
                    .addComponent(PeopleAsAssetCheckbox)
                    .addComponent(StepStoneAssets))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProcessAsAssets)
                    .addComponent(IntangibleAssetsCheckbox))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(scoreLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Threat Agent", jPanel2);

        jLabel8.setText("Attack method");

        jLabel9.setText("Description");

        submitButton.setText("Create New Attack Method");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(descriptionTA, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attackMethodTF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(attackMethodTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(descriptionTA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Create Attack Method", jPanel3);

        jLabel10.setText("Attack method");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Description");

        descriptionLabel.setText("Description");

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Apply the Attack Method");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionLabel)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descriptionLabel)
                        .addGap(93, 93, 93)))
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Select an Attack Method", jPanel4);

        jPanel1.setName("probabilityPanel"); // NOI18N

        jLabel1.setText("Probability");

        jLabel2.setText("Asset");

        editButton.setText("Apply");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        assetCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(probabilityTF)
                            .addComponent(assetCombo, 0, 184, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(probabilityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(assetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(editButton)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Probability", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

       // pack();
        this.setSize(600,500);
        this.setResizable(false);
    }// </editor-fold>                        

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.out.println("Pro:"+probabilityTF.getText()+" On Asset");
    }                                          

    private void ComputerMeansCheckboxActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        System.out.println(ComputerMeansCheckbox.isSelected());
         if (ComputerMeansCheckbox.isSelected())
           taService.meansSetter("add");
         else
           taService.meansSetter("delete");
         scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                                     

    private void motivationComboActionPerformed(java.awt.event.ActionEvent evt) {                                                
       System.out.println( motivationCombo.getSelectedItem());
       taService.motivationSetter(motivationCombo.getSelectedItem().toString());
       scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                               

    private void capabilitiesComboActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // System.out.println(capabilitiesCombo.getSelectedItem());
        taService.capabilitiesSetter(capabilitiesCombo.getSelectedItem().toString());
         scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                                 

    private void opportunitiesComboActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        System.out.println( opportunitiesCombo.getSelectedItem());
        taService.opportunitiesSetter(opportunitiesCombo.getSelectedItem().toString());
         scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                                  

    private void PeopleAsAssetCheckboxActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       if (PeopleAsAssetCheckbox.isSelected())
           taService.meansSetter("add");
       else
           taService.meansSetter("delete");
       scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                                     

    private void StepStoneAssetsActionPerformed(java.awt.event.ActionEvent evt) {                                                
        if (StepStoneAssets.isSelected())
           taService.meansSetter("add");
        else
           taService.meansSetter("delete");
        scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                               

    private void ProcessAsAssetsActionPerformed(java.awt.event.ActionEvent evt) {                                                
         if (ProcessAsAssets.isSelected())
           taService.meansSetter("add");
         else
           taService.meansSetter("delete");
         scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                               

    private void IntangibleAssetsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {                                                         
           if (IntangibleAssetsCheckbox.isSelected())
                taService.meansSetter("add");
           else
           taService.meansSetter("delete");
           scoreLabel.setText(Double.toString(taService.scoreEvaluator()));
    }                                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox ComputerMeansCheckbox;
    private javax.swing.JCheckBox IntangibleAssetsCheckbox;
    private javax.swing.JCheckBox PeopleAsAssetCheckbox;
    private javax.swing.JCheckBox ProcessAsAssets;
    private javax.swing.JCheckBox StepStoneAssets;
    private javax.swing.JComboBox<String> assetCombo;
    private javax.swing.JTextField attackMethodTF;
    private javax.swing.JComboBox<String> capabilitiesCombo;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField descriptionTA;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> motivationCombo;
    private javax.swing.JComboBox<String> opportunitiesCombo;
    private javax.swing.JTextField probabilityTF;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration                   
}
